<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-KQ2N0T6" failures="1" tests="2" name="Mentor.LoginTest" time="16.061" errors="0" timestamp="2023-08-09T20:06:16 EEST" skipped="0">
  <testcase classname="Mentor.LoginTest" name="badLogin" time="8.710">
    <failure message="expected [null] but found [[[ChromeDriver: chrome on windows (19f3d3bda4ee2b46bdf1f5fd995d503e)] -&gt; css selector: p.lead.text-danger]]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [null] but found [[[ChromeDriver: chrome on windows (19f3d3bda4ee2b46bdf1f5fd995d503e)] -> css selector: p.lead.text-danger]]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotSame(Assert.java:1574)
at org.testng.Assert.assertNull(Assert.java:1507)
at org.testng.Assert.assertNull(Assert.java:1495)
at org.example.Mentor.Pages.LoginPage.verifyBadLogin(LoginPage.java:22)
at Mentor.LoginTest.badLogin(LoginTest.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- badLogin -->
  <testcase classname="Mentor.LoginTest" name="successfulLogin" time="7.351"/>
</testsuite> <!-- Mentor.LoginTest -->
